name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']   # keep in sync with your local python

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Lint
        run: |
          pip install black==24.8.0 isort==5.13.2
          black --check .
          isort --check-only . --profile black

      - name: Test
        env:
          MPLBACKEND: Agg
        run: |
          pip install pytest
          pytest -q

      - name: Test
        env:
          MPLBACKEND: Agg
        run: |
          pip install pytest
          pytest -q
